import { Post } from './types';

type Translator = (key: string) => string;

export const getDummyPosts = (t: Translator): Post[] => [
  {
    id: 1,
    slug: 'le-futur-brillant-de-lenergie-solaire',
    title: t('posts.post1.title'),
    excerpt: t('posts.post1.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.solar'),
    author: { name: 'Dr. Eva Lerois', avatarUrl: 'https://i.pravatar.cc/150?u=eva' },
    date: '12 Septembre, 2025',
    views: 1200,
    likes: 250,
  },
  {
    id: 2,
    title: t('posts.post2.title'),
    slug: 'stockage-energie-batteries-demain',
    excerpt: t('posts.post2.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Marc Dubois', avatarUrl: 'https://i.pravatar.cc/150?u=marc' },
    date: '10 Septembre, 2025',
    views: 2300,
    likes: 450,
  },
  {
    id: 3,
    title: t('posts.post3.title'),
    slug: 'hydrogene-vert-utopie-revolution',
    excerpt: t('posts.post3.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Chloé Renaud', avatarUrl: 'https://i.pravatar.cc/150?u=chloe' },
    date: '8 Septembre, 2025',
    views: 3400,
    likes: 600,
  },
  {
    id: 4,
    title: t('posts.post4.title'),
    slug: 'eolien-offshore-revolution-energetique',
    excerpt: t('posts.post4.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Jean Martin', avatarUrl: 'https://i.pravatar.cc/150?u=jean' },
    date: '6 Septembre, 2025',
    views: 1800,
    likes: 320,
  },
  {
    id: 5,
    title: t('posts.post5.title'),
    slug: 'smart-grids-intelligence-energie',
    excerpt: t('posts.post5.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Laura Beny', avatarUrl: 'https://i.pravatar.cc/150?u=laura' },
    date: '5 Septembre, 2025',
    views: 2100,
    likes: 410,
  },
  {
    id: 6,
    title: t('posts.post6.title'),
    slug: 'biomasse-energie-verte-sous-estimee',
    excerpt: t('posts.post6.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'Paul Garnier', avatarUrl: 'https://i.pravatar.cc/150?u=paul' },
    date: '3 Septembre, 2025',
    views: 1500,
    likes: 280,
  },
  {
    id: 7,
    title: t('posts.post7.title'),
    slug: 'panneaux-solaires-souples',
    excerpt: t('posts.post7.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.solar'),
    author: { name: 'Sophie Leclerc', avatarUrl: 'https://i.pravatar.cc/150?u=sophie' },
    date: '1 Septembre, 2025',
    views: 2800,
    likes: 520,
  },
  {
    id: 8,
    title: t('posts.post8.title'),
    slug: 'hydroelectricite-petite-taille',
    excerpt: t('posts.post8.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'Thomas Leroy', avatarUrl: 'https://i.pravatar.cc/150?u=thomas' },
    date: '29 Août, 2025',
    views: 1900,
    likes: 350,
  },
  {
    id: 9,
    title: t('posts.post9.title'),
    slug: 'ia-au-service-energie',
    excerpt: t('posts.post9.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Alice Dupont', avatarUrl: 'https://i.pravatar.cc/150?u=alice' },
    date: '27 Août, 2025',
    views: 3100,
    likes: 580,
  },
  {
    id: 10,
    title: t('posts.post10.title'),
    slug: 'geothermie-energie-cachee',
    excerpt: t('posts.post10.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Nicolas Bernard', avatarUrl: 'https://i.pravatar.cc/150?u=nicolas' },
    date: '25 Août, 2025',
    views: 2600,
    likes: 490,
  },
  {
    id: 11,
    title: t('posts.post11.title'),
    slug: 'recyclage-panneaux-solaires',
    excerpt: t('posts.post11.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'David Morel', avatarUrl: 'https://i.pravatar.cc/150?u=david' },
    date: '23 Août, 2025',
    views: 2200,
    likes: 400,
  },
  {
    id: 12,
    title: t('posts.post12.title'),
    slug: 'micro-reseaux-energetiques',
    excerpt: t('posts.post12.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Julien Robert', avatarUrl: 'https://i.pravatar.cc/150?u=julien' },
    date: '21 Août, 2025',
    views: 2400,
    likes: 430,
  },
  {
    id: 13,
    title: t('posts.post13.title'),
    slug: 'transition-energetique-afrique',
    excerpt: t('posts.post13.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'Fatou Ndiaye', avatarUrl: 'https://i.pravatar.cc/150?u=fatou' },
    date: '19 Août, 2025',
    views: 3800,
    likes: 700,
  },
  {
    id: 14,
    title: t('posts.post14.title'),
    slug: 'villes-vertes-energie-urbaine',
    excerpt: t('posts.post14.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Olivier Rey', avatarUrl: 'https://i.pravatar.cc/150?u=olivier' },
    date: '17 Août, 2025',
    views: 2900,
    likes: 530,
  },
  {
    id: 15,
    title: t('posts.post15.title'),
    slug: 'mobilite-electrique-defis-opportunites',
    excerpt: t('posts.post15.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.transport'),
    author: { name: 'Camille Petit', avatarUrl: 'https://i.pravatar.cc/150?u=camille' },
    date: '15 Août, 2025',
    views: 3200,
    likes: 610,
  },
  {
    id: 16,
    title: t('posts.post16.title'),
    slug: 'blockchain-energie-transactions',
    excerpt: t('posts.post16.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Hugo Lambert', avatarUrl: 'https://i.pravatar.cc/150?u=hugo' },
    date: '13 Août, 2025',
    views: 2700,
    likes: 500,
  },
  {
    id: 17,
    title: t('posts.post17.title'),
    slug: 'agrivoltaisme-cultiver-produire-energie',
    excerpt: t('posts.post17.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.solar'),
    author: { name: 'Manon Girard', avatarUrl: 'https://i.pravatar.cc/150?u=manon' },
    date: '11 Août, 2025',
    views: 3500,
    likes: 650,
  },
  {
    id: 18,
    title: t('posts.post18.title'),
    slug: 'energie-big-data-alliance',
    excerpt: t('posts.post18.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Romain Lefevre', avatarUrl: 'https://i.pravatar.cc/150?u=romain' },
    date: '9 Août, 2025',
    views: 3000,
    likes: 550,
  },
  {
    id: 19,
    title: t('posts.post19.title'),
    slug: 'defis-transport-hydrogene',
    excerpt: t('posts.post19.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.transport'),
    author: { name: 'Claire Dubreuil', avatarUrl: 'https://i.pravatar.cc/150?u=claire' },
    date: '7 Août, 2025',
    views: 2500,
    likes: 480,
  },
  {
    id: 20,
    title: t('posts.post20.title'),
    slug: 'energie-economie-sociale-solidaire',
    excerpt: t('posts.post20.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'Yannick Perrot', avatarUrl: 'https://i.pravatar.cc/150?u=yannick' },
    date: '5 Août, 2025',
    views: 2000,
    likes: 380,
  },
  {
    id: 21,
    title: t('posts.post21.title'),
    slug: 'solaire-urbain-integration',
    excerpt: t('posts.post21.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.solar'),
    author: { name: 'Amélie Roche', avatarUrl: 'https://i.pravatar.cc/150?u=amelie' },
    date: '3 Août, 2025',
    views: 3300,
    likes: 620,
  },
  {
    id: 22,
    title: t('posts.post22.title'),
    slug: 'ia-transport-electrique',
    excerpt: t('posts.post22.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.transport'),
    author: { name: 'Lucas Meyer', avatarUrl: 'https://i.pravatar.cc/150?u=lucas' },
    date: '1 Août, 2025',
    views: 3600,
    likes: 680,
  },
  {
    id: 23,
    title: t('posts.post23.title'),
    slug: 'solaire-concentre-chaleur',
    excerpt: t('posts.post23.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.solar'),
    author: { name: 'Élodie Barre', avatarUrl: 'https://i.pravatar.cc/150?u=elodie' },
    date: '30 Juillet, 2025',
    views: 2900,
    likes: 540,
  },
  {
    id: 24,
    title: t('posts.post24.title'),
    slug: 'materiaux-stockage-energie',
    excerpt: t('posts.post24.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.innovation'),
    author: { name: 'Mathieu Colin', avatarUrl: 'https://i.pravatar.cc/150?u=mathieu' },
    date: '28 Juillet, 2025',
    views: 3100,
    likes: 590,
  },
  {
    id: 25,
    title: t('posts.post25.title'),
    slug: 'durabilite-energies-renouvelables',
    excerpt: t('posts.post25.excerpt'),
    imageUrl: '/images.jpeg',
    category: t('categories.sustainability'),
    author: { name: 'Sarah Fontaine', avatarUrl: 'https://i.pravatar.cc/150?u=sarah' },
    date: '26 Juillet, 2025',
    views: 2800,
    likes: 510,
  }
];