import { Post } from './types';

export const DUMMY_POSTS: Post[] = [
  {
    id: 1,
    slug: 'le-futur-brillant-de-lenergie-solaire',
    title: 'Le Futur Brillant de l\'Énergie Solaire Photovoltaïque',
    excerpt: 'Les avancées technologiques récentes dans les cellules photovoltaïques promettent une efficacité accrue et des coûts réduits, positionnant le solaire comme un pilier de la transition énergétique mondiale.',
    imageUrl: '/images.jpeg',
    category: 'Solaire',
    author: { name: 'Dr. Eva Lerois', avatarUrl: 'https://i.pravatar.cc/150?u=eva' },
    date: '12 Septembre, 2025',
    views: 1200,
    likes: 250,
  },
  {
    id: 2,
    title: 'Stockage d\'Énergie : Le Défi des Batteries de Demain',
    slug: 'stockage-energie-batteries-demain',
    excerpt: 'Comment les nouvelles Innovations de batteries, au-delà du lithium-ion, vont-elles révolutionner notre capacité à stocker\'l\'énergie renouvelable et stabiliser les réseaux électriques ?',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Marc Dubois', avatarUrl: 'https://i.pravatar.cc/150?u=marc' },
    date: '10 Septembre, 2025',
    views: 2300,
    likes: 450,
  },
  {
    id: 3,
    title: 'L\'Hydrogène Vert : Utopie ou Révolution Énergétique ?',
    slug: 'hydrogene-vert-utopie-revolution',
    excerpt: 'L\'hydrogène produit par électrolyse de l\'eau à partir d\'énergies renouvelables est au cœur des stratégies de décarbonation. Analysons son potentiel et les obstacles à surmonter.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Chloé Renaud', avatarUrl: 'https://i.pravatar.cc/150?u=chloe' },
    date: '8 Septembre, 2025',
    views: 3400,
    likes: 600,
  },
  {
    id: 4,
    title: 'Éolien Offshore : Le Vent de la Révolution Énergétique',
    slug: 'eolien-offshore-revolution-energetique',
    excerpt: 'Avec des turbines de plus en plus puissantes, l’éolien offshore devient une solution incontournable pour répondre à la demande énergétique croissante.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Jean Martin', avatarUrl: 'https://i.pravatar.cc/150?u=jean' },
    date: '6 Septembre, 2025',
    views: 1800,
    likes: 320,
  },
  {
    id: 5,
    title: 'Smart Grids : L’Intelligence au Service de l’Énergie',
    slug: 'smart-grids-intelligence-energie',
    excerpt: 'Les réseaux intelligents permettent une gestion dynamique de l’énergie, améliorant la stabilité et réduisant les pertes.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Laura Beny', avatarUrl: 'https://i.pravatar.cc/150?u=laura' },
    date: '5 Septembre, 2025',
    views: 2100,
    likes: 410,
  },
  {
    id: 6,
    title: 'Biomasse : Une Énergie Verte Trop Souvent Sous-Estimée',
    slug: 'biomasse-energie-verte-sous-estimee',
    excerpt: 'La biomasse joue un rôle majeur dans le mix énergétique durable. Focus sur ses avantages et ses limites.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'Paul Garnier', avatarUrl: 'https://i.pravatar.cc/150?u=paul' },
    date: '3 Septembre, 2025',
    views: 1500,
    likes: 280,
  },
  {
    id: 7,
    title: 'La Révolution des Panneaux Solaires Souples',
    slug: 'panneaux-solaires-souples',
    excerpt: 'Les panneaux solaires flexibles ouvrent la voie à des applications inédites, de l’architecture aux objets connectés.',
    imageUrl: '/images.jpeg',
    category: 'Solaire',
    author: { name: 'Sophie Leclerc', avatarUrl: 'https://i.pravatar.cc/150?u=sophie' },
    date: '1 Septembre, 2025',
    views: 2800,
    likes: 520,
  },
  {
    id: 8,
    title: 'Hydroélectricité de Petite Taille : L’Avenir des Rivières',
    slug: 'hydroelectricite-petite-taille',
    excerpt: 'Les petites centrales hydroélectriques représentent une solution locale et durable pour les communautés.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'Thomas Leroy', avatarUrl: 'https://i.pravatar.cc/150?u=thomas' },
    date: '29 Août, 2025',
    views: 1900,
    likes: 350,
  },
  {
    id: 9,
    title: 'L’Intelligence Artificielle au Service de l’Énergie',
    slug: 'ia-au-service-energie',
    excerpt: 'De la maintenance prédictive aux prévisions de consommation, l’IA transforme la manière dont nous produisons et consommons l’énergie.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Alice Dupont', avatarUrl: 'https://i.pravatar.cc/150?u=alice' },
    date: '27 Août, 2025',
    views: 3100,
    likes: 580,
  },
  {
    id: 10,
    title: 'La Géothermie : L’Énergie Cachée sous nos Pieds',
    slug: 'geothermie-energie-cachee',
    excerpt: 'La chaleur de la Terre est une ressource abondante et stable, encore sous-exploitée.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Nicolas Bernard', avatarUrl: 'https://i.pravatar.cc/150?u=nicolas' },
    date: '25 Août, 2025',
    views: 2600,
    likes: 490,
  },
  {
    id: 11,
    title: 'Recyclage des Panneaux Solaires : Un Défi à Relever',
    slug: 'recyclage-panneaux-solaires',
    excerpt: 'À mesure que les installations vieillissent, la gestion des déchets photovoltaïques devient un enjeu crucial.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'David Morel', avatarUrl: 'https://i.pravatar.cc/150?u=david' },
    date: '23 Août, 2025',
    views: 2200,
    likes: 400,
  },
  {
    id: 12,
    title: 'Micro-Réseaux Énergétiques : L’Autonomie Locale',
    slug: 'micro-reseaux-energetiques',
    excerpt: 'Les micro-réseaux permettent à des zones isolées ou urbaines d’assurer une résilience énergétique accrue.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Julien Robert', avatarUrl: 'https://i.pravatar.cc/150?u=julien' },
    date: '21 Août, 2025',
    views: 2400,
    likes: 430,
  },
  {
    id: 13,
    title: 'La Transition Énergétique en Afrique',
    slug: 'transition-energetique-afrique',
    excerpt: 'Le continent africain se positionne comme un leader potentiel grâce à ses ressources naturelles abondantes.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'Fatou Ndiaye', avatarUrl: 'https://i.pravatar.cc/150?u=fatou' },
    date: '19 Août, 2025',
    views: 3800,
    likes: 700,
  },
  {
    id: 14,
    title: 'Les Villes Vertes et la Gestion de l’Énergie Urbaine',
    slug: 'villes-vertes-energie-urbaine',
    excerpt: 'Les smart cities s’appuient sur des Innovations innovantes pour réduire leur empreinte énergétique.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Olivier Rey', avatarUrl: 'https://i.pravatar.cc/150?u=olivier' },
    date: '17 Août, 2025',
    views: 2900,
    likes: 530,
  },
  {
    id: 15,
    title: 'La Mobilité Électrique : Défis et Opportunités',
    slug: 'mobilite-electrique-defis-opportunites',
    excerpt: 'Les véhicules électriques s’imposent progressivement, mais leur déploiement soulève de nouveaux défis énergétiques.',
    imageUrl: '/images.jpeg',
    category: 'Transport',
    author: { name: 'Camille Petit', avatarUrl: 'https://i.pravatar.cc/150?u=camille' },
    date: '15 Août, 2025',
    views: 3200,
    likes: 610,
  },
  {
    id: 16,
    title: 'Blockchain et Énergie : Vers des Transactions Décentralisées',
    slug: 'blockchain-energie-transactions',
    excerpt: 'La blockchain promet de révolutionner la gestion et l’échange de l’énergie entre producteurs et consommateurs.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Hugo Lambert', avatarUrl: 'https://i.pravatar.cc/150?u=hugo' },
    date: '13 Août, 2025',
    views: 2700,
    likes: 500,
  },
  {
    id: 17,
    title: 'Agrivoltaïsme : Cultiver et Produire de l’Énergie',
    slug: 'agrivoltaisme-cultiver-produire-energie',
    excerpt: 'L’agrivoltaïsme combine agriculture et panneaux solaires pour une optimisation de l’espace et des ressources.',
    imageUrl: '/images.jpeg',
    category: 'Solaire',
    author: { name: 'Manon Girard', avatarUrl: 'https://i.pravatar.cc/150?u=manon' },
    date: '11 Août, 2025',
    views: 3500,
    likes: 650,
  },
  {
    id: 18,
    title: 'Énergie et Big Data : Une Alliance Stratégique',
    slug: 'energie-big-data-alliance',
    excerpt: 'L’analyse massive des données permet de prédire la demande énergétique et d’optimiser la production.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Romain Lefevre', avatarUrl: 'https://i.pravatar.cc/150?u=romain' },
    date: '9 Août, 2025',
    views: 3000,
    likes: 550,
  },
  {
    id: 19,
    title: 'Les Défis du Transport Hydrogène',
    slug: 'defis-transport-hydrogene',
    excerpt: 'Transporter l’hydrogène vert reste un défi logistique et économique à surmonter.',
    imageUrl: '/images.jpeg',
    category: 'Transport',
    author: { name: 'Claire Dubreuil', avatarUrl: 'https://i.pravatar.cc/150?u=claire' },
    date: '7 Août, 2025',
    views: 2500,
    likes: 480,
  },
  {
    id: 20,
    title: 'Énergie et Économie Sociale et Solidaire',
    slug: 'energie-economie-sociale-solidaire',
    excerpt: 'Les coopératives énergétiques locales permettent une meilleure implication citoyenne dans la transition.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'Yannick Perrot', avatarUrl: 'https://i.pravatar.cc/150?u=yannick' },
    date: '5 Août, 2025',
    views: 2000,
    likes: 380,
  },
  {
    id: 21,
    title: 'Solaire Urbain : Intégrer l’Énergie au Cœur des Villes',
    slug: 'solaire-urbain-integration',
    excerpt: 'Les panneaux intégrés aux bâtiments deviennent une composante essentielle de l’urbanisme durable.',
    imageUrl: '/images.jpeg',
    category: 'Solaire',
    author: { name: 'Amélie Roche', avatarUrl: 'https://i.pravatar.cc/150?u=amelie' },
    date: '3 Août, 2025',
    views: 3300,
    likes: 620,
  },
  {
    id: 22,
    title: 'Intelligence Artificielle et Transport Électrique',
    slug: 'ia-transport-electrique',
    excerpt: 'L’IA optimise les flux de recharge et améliore l’efficacité des flottes de véhicules électriques.',
    imageUrl: '/images.jpeg',
    category: 'Transport',
    author: { name: 'Lucas Meyer', avatarUrl: 'https://i.pravatar.cc/150?u=lucas' },
    date: '1 Août, 2025',
    views: 3600,
    likes: 680,
  },
  {
    id: 23,
    title: 'Solaire Concentré : Quand la Lumière Devient Chaleur',
    slug: 'solaire-concentre-chaleur',
    excerpt: 'Les centrales solaires thermodynamiques utilisent des miroirs pour concentrer la lumière et produire de l’énergie.',
    imageUrl: '/images.jpeg',
    category: 'Solaire',
    author: { name: 'Élodie Barre', avatarUrl: 'https://i.pravatar.cc/150?u=elodie' },
    date: '30 Juillet, 2025',
    views: 2900,
    likes: 540,
  },
  {
    id: 24,
    title: 'Innovation dans les Matériaux de Stockage d’Énergie',
    slug: 'materiaux-stockage-energie',
    excerpt: 'De nouveaux matériaux comme le graphène ouvrent des perspectives inédites pour les batteries.',
    imageUrl: '/images.jpeg',
    category: 'Innovation',
    author: { name: 'Mathieu Colin', avatarUrl: 'https://i.pravatar.cc/150?u=mathieu' },
    date: '28 Juillet, 2025',
    views: 3100,
    likes: 590,
  },
  {
    id: 25,
    title: 'Durabilité et Énergies Renouvelables : Un Duo Gagnant',
    slug: 'durabilite-energies-renouvelables',
    excerpt: 'Associer durabilité et production énergétique est essentiel pour assurer un avenir viable.',
    imageUrl: '/images.jpeg',
    category: 'Durabilité',
    author: { name: 'Sarah Fontaine', avatarUrl: 'https://i.pravatar.cc/150?u=sarah' },
    date: '26 Juillet, 2025',
    views: 2800,
    likes: 510,
  }
];
