import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "@/styles/globals.css";
import { NextIntlClientProvider } from "next-intl";

const libreFranklin = Libre_Franklin({
  subsets: [
    "latin",
  ],
  variable: "--font-libre-franklin",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${libreFranklin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
